name: CI
on:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: example
        shell: bash
        run: scripts/ci_test.py
